# Generated by Django 4.1.3 on 2022-11-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_order_estimate_date_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover', verbose_name='cover'),
        ),
    ]
